# Enable the use of CAC certificates for authentication
# sudo yum install pcsc-tools pcsc-lite coolkey

- name: Include cert variables
  include_vars:
    file: defaults/cac.yml
    name: cac

- name: Create tmp certs folder
  file:
    path: /tmp/certs
    state: directory

- name: Unpack certs
  unarchive:
    src: "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/certificates_pkcs7_DoD.zip"
    dest: /tmp/certs
    remote_src: yes

- name: Convert certificate format
  command: openssl pkcs7 -print_certs -in Certificates_PKCS7_v5.9_DoD.pem.p7b -out /tmp/certs/DoD_Certs.pem
  args:
    chdir: /tmp/certs/Certificates_PKCS7_v5.9_DoD
    creates: /tmp/certs/DoD_Certs.pem

- name: Copy certs
  become: true
  become_user: root
  copy:
   src: /tmp/certs/DoD_Certs.pem
   dest: /etc/pki/ca-trust/source/anchors/
   owner: root
   group: root
   mode: 0755

- name: update-ca-trust
  become: true
  become_user: root
  command: update-ca-trust

- name: Install the latest version of SmartCard software
  become: true
  become_user: root
  package:
    name:
      - pcsc-tools
      - opensc
    state: latest
  when: ansible_distribution_major_version == '8'

- name: Install the SmartCard software - EL7
  become: true
  become_user: root
  package:
    name:
      - pcsc-tools
      - pcsc-lite
      - coolkey
    state: latest
  when: ansible_distribution_major_version == '7'

# sudo systemctl enable pcscd
- name: Start and enable pcscd
  service:
    name: pcscd
    state: started
    enabled: yes

- name: Install certificates to ~/.pki/nssdb/
  command: |
    certutil -A -d 'sql:/home/{{ install_user if change_user else lookup('env', 'USER') }}/.pki/nssdb/'
    -n '{{ item.name }}'
    -t '{{ item.trust }}'
    -i '{{ item.path }}'
  with_items: '{{ cac.nssdb_certificates }}'
  when : ansible_distribution_major_version == '7'
  changed_when: false

- name: Reminder to enable CAC support in Firefox (EL7)
  debug:
    msg: |
      On EL7, Firefox requires manually importing the CoolKey library to access CAC-enabled websites.

      Open Fire ☰ menu > Settings > Privacy & Security > scroll down to the Certificates section and click Security Devices. Click "Load" and:

        * enter "CoolKey CAC Module" (without quotes) as the module name.
        * enter "/usr/lib64/pkcs11/libcoolkeypk11.so" (without quotes) as the module filename.
  when: ansible_distribution_major_version | int < 8
